django-stuff/dlog/urls.py
from django.urls import path

from . import views

app_name = "dlog"
urlpatterns: list = [
    # ex: /dlog/
    path("", views.index, name="index"), 
    # ex: /dlog/form
    path("form/", views.form, name="form"),
    path("record/", views.record, name="record"),
]

django-stuff/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns: list = [
    path('dlog/', include('dlog.urls')),
    path('admin/', admin.site.urls),
]

django-stuff/dlog/models.py
from django.db import models

# How many cups of kibble I fed goose
class FoodAmount(models.Model):
    feed_date = models.DateField()
    cups_of_kibble = models.DecimalField(max_digits=4, decimal_places=1)

    # return a string for the record of cups of kibble fed
    def __str__(self):
        return f'{self.feed_date} {self.cups_of_kibble} cups'

# Notes and observations

class Observation(models.Model):
    note_weight_date = models.ForeignKey(FoodAmount, on_delete=models.CASCADE)
    weight = models.IntegerField()
    note = models.TextField()

    # returns weight and notes
    def __str__(self):
        return f'{self.weight} lbs and/or notes for this day: {self.note}'

django-stuff/dlog/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from .models import FoodAmount,Observation

def index(request):
    latest_food_amounts_list = FoodAmount.objects.order_by("-feed_date")[:5]
    # get observations, notes and weight
    if latest_food_amounts_list.observation_set.exists():
        observations = latest_food_amounts_list.observation_set.all()

    template = loader.get_template("dlog/index.html")
    context = {"latest_food_amounts_list": latest_food_amounts_list}
    return HttpResponse(template.render(context, request))


def form(request):
    # template = loader.get_template("dlog/form.html")
    return render(request, "dlog/form.html")


def record(request):
    feed_date = request.POST['feed_date']
    # print("*" * 10)
    # print(feed_date)
    # print("*" * 10)
    cups_of_kibble = request.POST.get('cups_of_kibble')
    feed_info = FoodAmount(
        feed_date=feed_date, 
        cups_of_kibble=cups_of_kibble
    )
    weight = request.POST.get('weight')
    note = request.POST.get('note')
    feed_info.save()
    feed_info.observation_set.create(
        weight=weight,
        note=note
    )

    
    return HttpResponseRedirect("/dlog/")

django-stuff/dlog/templates/dlog/form.html
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8" />
    <title>Dog Log Form page</title>
  </head>
  <body>
    <fieldset>
      <legend><h1>Enter Goose Information Please</h1></legend>
      <form action="{% url 'dlog:record'  %}" method="post">
        {% csrf_token %}
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        <label for="feed_date">Feed Date(optional):</label>
        <input type="date" id="feed_date" name="feed_date"> 
        <label for="cups_of_kibble">How much kibble did little Goose eat?</label>
        <input type="number" id="cups_of_kibble" name="cups_of_kibble" min="1" max="5"> 
        <label for="weight">How much does little Goose weigh?</label>
        <input type="number" id="weight" name="weight" min="1" max="75">
        <label for="note">Any notes for the day?</label>
        <textarea id="note" type="text" name="note" rows="4" cols="50" placeholder="Any meds given, bowel movements to report, notes on food..."></textarea>
        <input type="submit" value="Record">
      </form>
    </fieldset>
  </body>
</html>

django-stuff/dlog/templates/dlog/index.html
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8" />
    <title>Dog Log Index page</title>
  </head>
  <body>
    <table summary="keeping-track-of-dog">
      <tr>
        <th>Date</th>
        <th>Amount of kibble for day - cups</th>
      </tr>
    {% if latest_food_amounts_list %}
        
        {% for amount in latest_food_amounts_list %}
            <tr>
            <!-- # todo test if notes and weight exist if, if not then don't render as link, just as text, hmmm.... 
             or just display on table and handle null values in model string return, hmmm...-->
            <td><a href="/details/">{{ amount.feed_date }}</a></td>
            <td>{{ amount.cups_of_kibble }}</td>
            </tr>
        {% endfor %}
    {% else %}
        <p>No entries available</p>
    {% endif %}
    </table>
  </body>
</html>